# _config.yml

title:      'Hyeonrae.Wiki'
url:        'https://hyeonrae.github.io'
baseurl:    '/wiki'

#exclude:        [README.md, LICENSE, Gemfile*, Rakefile, vendor]
permalink:      pretty


# Enable or disable the site search
search_enabled: true

# Set the search token separator for hyphenated-word search:
search_tokenizer_separator: /[\s/]+/

# Enable or disable heading anchors
heading_anchors: true

aux_links:
  'GitHub':
    - 'https://github.com/hyeonrae/'

# Color scheme currently only supports "dark" or nil (default)
color_scheme: nil

# Google Analytics Tracking (optional)
# e.g, UA-1234567-89
ga_tracking: UA-2709176-10

plugins:
  - jekyll-seo-tag
